name: Build, Test, and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository.
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Go.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # Cache Go modules.
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # # Run tests.
      # - name: Run Tests
      #   run: go test -v ./...

      # Bump version and create tag.
      - name: Bump Version and Create Tag
        id: bump_version
        uses: anothrnick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DEFAULT_BRANCH: "main"
          RELEASE_BRANCHES: "main"
          WITH_V: true

      # Build the kpeek binary with the version injected.
      - name: Build kpeek with version
        run: |
          echo "Building kpeek with version: ${{ steps.bump_version.outputs.new_tag }}"
          go build -ldflags "-X github.com/hacktivist123/kpeek/cmd.version=${{ steps.bump_version.outputs.new_tag }}" -o kpeek .

      # Set up QEMU for multi-arch builds.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push the Docker image using the locally built binary.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            coderblvck/kpeek:latest
            coderblvck/kpeek:${{ steps.bump_version.outputs.new_tag }}
          build-args: |
            KPEEK_VERSION=${{ steps.bump_version.outputs.new_tag }}
          cache-from: type=registry,ref=coderblvck/kpeek:buildcache
          cache-to: type=registry,ref=coderblvck/kpeek:buildcache,mode=max
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACCESS_TOKEN }}

      # Upload the built binary as an artifact
      - name: Upload kpeek binary
        uses: actions/upload-artifact@v4
        with:
          name: kpeek-binary
          path: kpeek

      # Create GitHub Release.
      - name: Create GitHub Release
        if: ${{ success() }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          release_name: "Release ${{ steps.bump_version.outputs.new_tag }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
